apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
type: Opaque
data:
  # Replace with your base64 encoded tunnel credentials JSON
  credentials.json: <BASE64_ENCODED_TUNNEL_CREDENTIALS>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-config
  namespace: cloudflare
data:
  config.yaml: |
    tunnel: <YOUR_TUNNEL_ID>
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
      - hostname: grafana.moclawr.com
        service: http://grafana-service.monitoring.svc.cluster.local:3000
      - service: http_status:404
